### PR TITLE
Features/school endpoint

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
- external.py
- schools_cleaned.ipynb

### Details
- update school endpoint
- was only returning high school
- cleaned schools csv (found out that a few cities were not fully scraped).

### Committed Features
- update school endpoint function

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will find and share school ratings with users.](https://trello.com/c/TpDUqMIk/34-ds-will-find-and-share-school-ratings-with-users)

**Review by lmelto — DISMISSED** [review]

**Review by bobbyhalljr — DISMISSED** [review]
Please delete the commented code if it is not needed. It looks like this one has conflicts as well in the same file. Let me know if you need help resolving them.

**Comment by jiobu1** [comment]
Need to look over schools.csv to make sure all schools were scraped from great schools.

**Review by ToddDiFronzo — APPROVED** [review]
Good fix

**Review by lmelto — APPROVED** [review]

**Review by bobbyhalljr — APPROVED** [review]

**Pull request merged**
