### PR TITLE
Feature/mobility scores

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
- ml.py

### Details
- create function for retrieving bike and bus scores
(Created as separate functions rather than adding to walkability function for speed - makes get data function run slower)

### Committed Features
- users can now see how the mobility scores of the desired city. 
- Answers the question if this is a pedestrian friendly city.

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will update walkability endpoint to include transit and bike scores](https://trello.com/c/qLAjQNlW/61-ds-will-update-walkability-endpoint-to-include-transit-and-bike-scores)

**Review by lmelto — DISMISSED** [review]

**Review by bobbyhalljr — DISMISSED** [review]
Looks like theres some merge conflicts. Let me know if you need any help resolving them before we merge it into main.

**Review by ToddDiFronzo — APPROVED** [review]
Looks fine

**Review by bobbyhalljr — APPROVED** [review]

**Review by lmelto — APPROVED** [review]

**Comment by jiobu1** [comment]
[DS will create endpoints for both web and iOS, utlizing the new data sets.](https://trello.com/c/XtxY8lD4/13-ds-will-create-endpoints-for-both-web-and-ios-utlizing-the-new-data-sets)

**Pull request merged**
