### PR TITLE
Update rental endpoint to account for none in pet policy

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
- external.py
- testing_external.py

### Details
update rental_listing to account for no cat or dog policy

### Committed Features
- updated rental_listing endpoint so user can get back 5 listings for their desired city without running into errors because of pet policy

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will create endpoints for both web and iOS, utlizing the new data sets.](https://trello.com/c/XtxY8lD4/13-ds-will-create-endpoints-for-both-web-and-ios-utlizing-the-new-data-sets)

**Comment by jiobu1** [comment]
[DS will show rental information for different cities](https://trello.com/c/0cq3peCX/12-ds-will-show-rental-information-for-different-cities)

**Review by lmelto — APPROVED** [review]
Looks good

**Review by ToddDiFronzo — APPROVED** [review]
Looks good

**Pull request merged**
