### PR TITLE
Cleanup/remove file

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
notebooks/data/update_lat_lon.ipynb

### Details
delete file since it was incomplete

### CODE REVIEW

**Comment by jiobu1** [comment]
[As a data scientists, I will review existing datasets.](https://trello.com/c/t8rsgrhO/8-as-a-data-scientists-i-will-review-existing-datasets)

**Review by ToddDiFronzo — DISMISSED** [review]
Looks good

**Review by lmelto — APPROVED** [review]
Looks good

**Review by ToddDiFronzo — APPROVED** [review]
Looks better :)

**Pull request merged**
