### PR TITLE
create population forecasting model and population endpoint

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
- move population folder from dataset/data to models
- viz.py

### Details
- create population forecast model 
- create population forecast visualization endpoint

### Committed Features
- users can see projected population growth

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will create an ML model that predicts population growth in a city](https://trello.com/c/6jy1kFn9/60-ds-will-create-an-ml-model-that-predicts-population-growth-in-a-city)

**Review by ToddDiFronzo — DISMISSED** [review]
Good

**Review by ToddDiFronzo — DISMISSED** [review]
Looks good

**Comment by jiobu1** [comment]
[DS will create endpoints for both web and iOS, utlizing the new data sets.](https://trello.com/c/XtxY8lD4/13-ds-will-create-endpoints-for-both-web-and-ios-utlizing-the-new-data-sets)

**Review by lmelto — APPROVED** [review]

**Review by bobbyhalljr — APPROVED** [review]

**Review by bobbyhalljr — APPROVED** [review]
There is a lot of commented code. We should try to clean it up a bit, unless it’s absolutely needed. Great job! 

Thanks !

**Pull request merged**
