### PR TITLE
Deploy to AWS

### PR DESCRIPTION
**Pull request by jiobu1**
# [AWS Elastic Beanstalk](https://trello.com/c/d3KGxbTh)
# [AWS RDS Postgres](https://trello.com/c/QbJ0VlZZ)

### Location:
- delete docker file

### Details:
- deploy to AWS Elastic Beanstalk - http://cityspire-a.eba-tgambvt2.us-east-1.elasticbeanstalk.com/
- uploaded csv to AWS RDS Postgres

### Committed Features:
Application is now deployed to AWS Elastic Beanstalk
Have separate DB from the previous one.

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will deploy endpoints on AWS ElasticBeanstalk](https://trello.com/c/d3KGxbTh/29-ds-will-deploy-endpoints-on-aws-elasticbeanstalk)

**Comment by jiobu1** [comment]
[DS will upload data to AWS RDS](https://trello.com/c/QbJ0VlZZ/30-ds-will-upload-data-to-aws-rds)

**Review by ToddDiFronzo — APPROVED** [review]
Looks good

**Review by lmelto — APPROVED** [review]
Looks good

**Pull request merged**
