### PR TITLE
Feature/rental_listing -> named branch incorrectly

### PR DESCRIPTION
**Pull request by jiobu1**
### Location:
- external.py

### Description:
- created rental_listing endpoint -> args: api key, city, state, property type

### Committed Features:
- users are able to query realtor.com and find rental listings in their desired city

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will show rental information for different cities](https://trello.com/c/0cq3peCX/12-ds-will-show-rental-information-for-different-cities)

**Review by lmelto — DISMISSED** [review]
Looks good

**Review by bobbyhalljr — DISMISSED** [review]

**Review by ToddDiFronzo — APPROVED** [review]
done

**Review by lmelto — APPROVED** [review]
Looks good

**Pull request merged**
