### PR TITLE
Features/school endpoint

### PR DESCRIPTION
**Pull request by jiobu1**
### Location
- external.py
- test_external.py

### Details
- Create endpoint for schools 

### Committed Features
- create schools listing endpoint
- users can query for school based on school category (pre-k, elementary, middle, and high school)

### CODE REVIEW

**Comment by jiobu1** [comment]
[DS will find and share school ratings with users.](https://trello.com/c/TpDUqMIk/34-ds-will-find-and-share-school-ratings-with-users)

**Review by lmelto — DISMISSED** [review]
Looks good

**Review by bobbyhalljr — DISMISSED** [review]

**Review by lmelto — APPROVED** [review]
Looks good

**Review by bobbyhalljr — APPROVED** [review]

**Comment by jiobu1** [comment]
[DS will create endpoints for both web and iOS, utlizing the new data sets.](https://trello.com/c/XtxY8lD4/13-ds-will-create-endpoints-for-both-web-and-ios-utlizing-the-new-data-sets)

**Pull request merged**
